const DEFAULT_OUTCOME = '';
const DEFAULT_BUDGET = 0;
const DEFAULT_WASTED = 0;
const DEFAULT_BALANCE = 0;

const ATTEMPT_UPDATE_AMOUNT = 4;
const ATTEMPT_UPDATE_FACTOR = 1.5;

export {
  ATTEMPT_UPDATE_AMOUNT,
  ATTEMPT_UPDATE_FACTOR,
  DEFAULT_BALANCE,
  DEFAULT_BUDGET,
  DEFAULT_OUTCOME,
  DEFAULT_WASTED,
};
